### ISSUE TITLE
Provide Sample test csv files that work with erb templates

### ISSUE THREAD

**Issue by hur1can3** [zdw/rubycsv#1]
Is there any way you could provide some sample csvs that work with the erb templates

This would be extremely helpful in coming up with a generic way to parse these files

**Comment by zdw** [comment]
I included an example using the savings.csv/.tpl files, as those were pretty easy to sanitize of personal data - see https://github.com/zdw/rubycsv/commit/e7e64c6bd96ebfd717ad94312d663e32bafd7968
